version: 2
updates:
  - package-ecosystem: gomod
    directory: /patient-service
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /patient-service
    schedule:
      interval: weekly