apiVersion: batch/v1
kind: Job
metadata:
  name: emr-service-migration
  namespace: selaras
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      name: emr-service-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: migrate/migrate:v4.18.2
          command:
            - -path=/migrations
            - -database=$(DATABASE_URL)
            - up
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: emr-service-secret
                  key: database-url
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: emr-service-migrations
