syntax = "proto3";

package patient.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/azuvicenna/selaras-services/patient-service/gen/patient/v1;patientv1";

// -----------------------------------------------------------------------------
// ENUMS
// -----------------------------------------------------------------------------

enum DocumentType {
  DOCUMENT_TYPE_UNSPECIFIED = 0;
  DOCUMENT_TYPE_KTP = 1;
  DOCUMENT_TYPE_BPJS_CARD = 2;
  DOCUMENT_TYPE_FAMILY_CARD = 3;       // Kartu Keluarga (KK)
  DOCUMENT_TYPE_REFERRAL_LETTER = 4;   // Surat Rujukan
  DOCUMENT_TYPE_OTHER = 5;
}

// -----------------------------------------------------------------------------
// DOMAIN MODEL
// -----------------------------------------------------------------------------

message PatientDocument {
  string id = 1;
  string patient_id = 2;                        // Foreign Key ke Patient.id
  DocumentType type = 3;                        // Jenis Dokumen
  string document_number = 4;                   // Nomor Dokumen (Nomor KTP/BPJS/Rujukan)
  string file_url = 5;                          // Path / Object Storage URL
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}