// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: patient/v1/patient.proto

package patientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_patient_v1_patient_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_patient_v1_patient_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{0}
}

type Patient struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MedicalRecordNo string                 `protobuf:"bytes,2,opt,name=medical_record_no,json=medicalRecordNo,proto3" json:"medical_record_no,omitempty"`
	Nik             string                 `protobuf:"bytes,3,opt,name=nik,proto3" json:"nik,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BirthDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender          Gender                 `protobuf:"varint,6,opt,name=gender,proto3,enum=patient.v1.Gender" json:"gender,omitempty"`
	Phone           string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Address         string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_patient_v1_patient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{0}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetMedicalRecordNo() string {
	if x != nil {
		return x.MedicalRecordNo
	}
	return ""
}

func (x *Patient) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

func (x *Patient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Patient) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *Patient) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *Patient) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Patient) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Patient) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Patient) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RegisterPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nik           string                 `protobuf:"bytes,1,opt,name=nik,proto3" json:"nik,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        Gender                 `protobuf:"varint,4,opt,name=gender,proto3,enum=patient.v1.Gender" json:"gender,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPatientRequest) Reset() {
	*x = RegisterPatientRequest{}
	mi := &file_patient_v1_patient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPatientRequest) ProtoMessage() {}

func (x *RegisterPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPatientRequest.ProtoReflect.Descriptor instead.
func (*RegisterPatientRequest) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPatientRequest) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

func (x *RegisterPatientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterPatientRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *RegisterPatientRequest) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *RegisterPatientRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterPatientRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPatientResponse) Reset() {
	*x = RegisterPatientResponse{}
	mi := &file_patient_v1_patient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPatientResponse) ProtoMessage() {}

func (x *RegisterPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPatientResponse.ProtoReflect.Descriptor instead.
func (*RegisterPatientResponse) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_patient_v1_patient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{3}
}

func (x *GetPatientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientResponse) Reset() {
	*x = GetPatientResponse{}
	mi := &file_patient_v1_patient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientResponse) ProtoMessage() {}

func (x *GetPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientResponse.ProtoReflect.Descriptor instead.
func (*GetPatientResponse) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{4}
}

func (x *GetPatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type ListPatientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsRequest) Reset() {
	*x = ListPatientsRequest{}
	mi := &file_patient_v1_patient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsRequest) ProtoMessage() {}

func (x *ListPatientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsRequest.ProtoReflect.Descriptor instead.
func (*ListPatientsRequest) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{5}
}

func (x *ListPatientsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPatientsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPatientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*Patient             `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsResponse) Reset() {
	*x = ListPatientsResponse{}
	mi := &file_patient_v1_patient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsResponse) ProtoMessage() {}

func (x *ListPatientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsResponse.ProtoReflect.Descriptor instead.
func (*ListPatientsResponse) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{6}
}

func (x *ListPatientsResponse) GetPatients() []*Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

type UpdatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nik           string                 `protobuf:"bytes,2,opt,name=nik,proto3" json:"nik,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        Gender                 `protobuf:"varint,5,opt,name=gender,proto3,enum=patient.v1.Gender" json:"gender,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientRequest) Reset() {
	*x = UpdatePatientRequest{}
	mi := &file_patient_v1_patient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientRequest) ProtoMessage() {}

func (x *UpdatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientRequest.ProtoReflect.Descriptor instead.
func (*UpdatePatientRequest) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePatientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePatientRequest) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

func (x *UpdatePatientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePatientRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *UpdatePatientRequest) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *UpdatePatientRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdatePatientRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientResponse) Reset() {
	*x = UpdatePatientResponse{}
	mi := &file_patient_v1_patient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientResponse) ProtoMessage() {}

func (x *UpdatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_v1_patient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientResponse.ProtoReflect.Descriptor instead.
func (*UpdatePatientResponse) Descriptor() ([]byte, []int) {
	return file_patient_v1_patient_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

var File_patient_v1_patient_proto protoreflect.FileDescriptor

const file_patient_v1_patient_proto_rawDesc = "" +
	"\n" +
	"\x18patient/v1/patient.proto\x12\n" +
	"patient.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x02\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11medical_record_no\x18\x02 \x01(\tR\x0fmedicalRecordNo\x12\x10\n" +
	"\x03nik\x18\x03 \x01(\tR\x03nik\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x129\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12*\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x12.patient.v1.GenderR\x06gender\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd5\x01\n" +
	"\x16RegisterPatientRequest\x12\x10\n" +
	"\x03nik\x18\x01 \x01(\tR\x03nik\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12*\n" +
	"\x06gender\x18\x04 \x01(\x0e2\x12.patient.v1.GenderR\x06gender\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\"H\n" +
	"\x17RegisterPatientResponse\x12-\n" +
	"\apatient\x18\x01 \x01(\v2\x13.patient.v1.PatientR\apatient\"#\n" +
	"\x11GetPatientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetPatientResponse\x12-\n" +
	"\apatient\x18\x01 \x01(\v2\x13.patient.v1.PatientR\apatient\"C\n" +
	"\x13ListPatientsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"G\n" +
	"\x14ListPatientsResponse\x12/\n" +
	"\bpatients\x18\x01 \x03(\v2\x13.patient.v1.PatientR\bpatients\"\xe3\x01\n" +
	"\x14UpdatePatientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03nik\x18\x02 \x01(\tR\x03nik\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12*\n" +
	"\x06gender\x18\x05 \x01(\x0e2\x12.patient.v1.GenderR\x06gender\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\"F\n" +
	"\x15UpdatePatientResponse\x12-\n" +
	"\apatient\x18\x01 \x01(\v2\x13.patient.v1.PatientR\apatient*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x022\xe2\x02\n" +
	"\x0ePatientService\x12Z\n" +
	"\x0fRegisterPatient\x12\".patient.v1.RegisterPatientRequest\x1a#.patient.v1.RegisterPatientResponse\x12K\n" +
	"\n" +
	"GetPatient\x12\x1d.patient.v1.GetPatientRequest\x1a\x1e.patient.v1.GetPatientResponse\x12Q\n" +
	"\fListPatients\x12\x1f.patient.v1.ListPatientsRequest\x1a .patient.v1.ListPatientsResponse\x12T\n" +
	"\rUpdatePatient\x12 .patient.v1.UpdatePatientRequest\x1a!.patient.v1.UpdatePatientResponseBSZQgithub.com/azuvicenna/selaras-services/patient-service/proto/patient/v1;patientv1b\x06proto3"

var (
	file_patient_v1_patient_proto_rawDescOnce sync.Once
	file_patient_v1_patient_proto_rawDescData []byte
)

func file_patient_v1_patient_proto_rawDescGZIP() []byte {
	file_patient_v1_patient_proto_rawDescOnce.Do(func() {
		file_patient_v1_patient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patient_v1_patient_proto_rawDesc), len(file_patient_v1_patient_proto_rawDesc)))
	})
	return file_patient_v1_patient_proto_rawDescData
}

var file_patient_v1_patient_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_patient_v1_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_patient_v1_patient_proto_goTypes = []any{
	(Gender)(0),                     // 0: patient.v1.Gender
	(*Patient)(nil),                 // 1: patient.v1.Patient
	(*RegisterPatientRequest)(nil),  // 2: patient.v1.RegisterPatientRequest
	(*RegisterPatientResponse)(nil), // 3: patient.v1.RegisterPatientResponse
	(*GetPatientRequest)(nil),       // 4: patient.v1.GetPatientRequest
	(*GetPatientResponse)(nil),      // 5: patient.v1.GetPatientResponse
	(*ListPatientsRequest)(nil),     // 6: patient.v1.ListPatientsRequest
	(*ListPatientsResponse)(nil),    // 7: patient.v1.ListPatientsResponse
	(*UpdatePatientRequest)(nil),    // 8: patient.v1.UpdatePatientRequest
	(*UpdatePatientResponse)(nil),   // 9: patient.v1.UpdatePatientResponse
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_patient_v1_patient_proto_depIdxs = []int32{
	10, // 0: patient.v1.Patient.birth_date:type_name -> google.protobuf.Timestamp
	0,  // 1: patient.v1.Patient.gender:type_name -> patient.v1.Gender
	10, // 2: patient.v1.Patient.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: patient.v1.Patient.updated_at:type_name -> google.protobuf.Timestamp
	10, // 4: patient.v1.RegisterPatientRequest.birth_date:type_name -> google.protobuf.Timestamp
	0,  // 5: patient.v1.RegisterPatientRequest.gender:type_name -> patient.v1.Gender
	1,  // 6: patient.v1.RegisterPatientResponse.patient:type_name -> patient.v1.Patient
	1,  // 7: patient.v1.GetPatientResponse.patient:type_name -> patient.v1.Patient
	1,  // 8: patient.v1.ListPatientsResponse.patients:type_name -> patient.v1.Patient
	10, // 9: patient.v1.UpdatePatientRequest.birth_date:type_name -> google.protobuf.Timestamp
	0,  // 10: patient.v1.UpdatePatientRequest.gender:type_name -> patient.v1.Gender
	1,  // 11: patient.v1.UpdatePatientResponse.patient:type_name -> patient.v1.Patient
	2,  // 12: patient.v1.PatientService.RegisterPatient:input_type -> patient.v1.RegisterPatientRequest
	4,  // 13: patient.v1.PatientService.GetPatient:input_type -> patient.v1.GetPatientRequest
	6,  // 14: patient.v1.PatientService.ListPatients:input_type -> patient.v1.ListPatientsRequest
	8,  // 15: patient.v1.PatientService.UpdatePatient:input_type -> patient.v1.UpdatePatientRequest
	3,  // 16: patient.v1.PatientService.RegisterPatient:output_type -> patient.v1.RegisterPatientResponse
	5,  // 17: patient.v1.PatientService.GetPatient:output_type -> patient.v1.GetPatientResponse
	7,  // 18: patient.v1.PatientService.ListPatients:output_type -> patient.v1.ListPatientsResponse
	9,  // 19: patient.v1.PatientService.UpdatePatient:output_type -> patient.v1.UpdatePatientResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_patient_v1_patient_proto_init() }
func file_patient_v1_patient_proto_init() {
	if File_patient_v1_patient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patient_v1_patient_proto_rawDesc), len(file_patient_v1_patient_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patient_v1_patient_proto_goTypes,
		DependencyIndexes: file_patient_v1_patient_proto_depIdxs,
		EnumInfos:         file_patient_v1_patient_proto_enumTypes,
		MessageInfos:      file_patient_v1_patient_proto_msgTypes,
	}.Build()
	File_patient_v1_patient_proto = out.File
	file_patient_v1_patient_proto_goTypes = nil
	file_patient_v1_patient_proto_depIdxs = nil
}
